#ifndef RETURN_CODE_H
#define RETURN_CODE_H

enum return_code {
    OK = 0,
    BAD_INPUT_ERROR = 1,
    OVERFLOW_ERROR = 2,
    BAD_POINTER_ERROR = 3,
    MEMORY_ALLOC_ERROR = 4,
    WRONG_ARGUMENTS_ERROR = 5,
    NOT_A_DOUBLE_ERROR = 6,
    NOT_AN_INTEGER_ERROR = 7,
    BAD_STREAM_ERROR = 8,
    FILE_ERROR = 9,
};

typedef enum TYPE_OF_PRINT {
    PRINT_TO_FILE_STREAM = 1,
    PRINT_TO_STRING = 2,
} TYPE_OF_PRINT;

#endif