#ifndef RETURN_CODE_H
#define RETURN_CODE_H

enum return_code {
    OK = 0,
    BAD_INPUT_ERROR = 1,
    OVERFLOW_ERROR = 2,
    BAD_POINTER_ERROR = 3,
    MEMORY_ALLOC_ERROR = 4,
    WRONG_ARGUMENTS_ERROR = 5,
    NOT_A_DOUBLE_ERROR = 6,
    PATH_IS_TOO_LONG_ERROR = 7,
    FILE_OPEN_ERROR = 8,
};

#endif